const tintColorLight = '#2f95dc';
const tintColorDark = '#fff';

export const COLORS = {
  light: {
    background: '#fff',
    backgroundAsh: '#F8F8F8',
    backgroundGray: '#F3F2F1',
    colorOne: '#F15A32',
    colorOneLight: '#F8C8BB',
    colorOneLight2: '#FDEDE9',
    colorOneDark: '#98350A',
    delete: '#EA001E',
    text: '#000',
    textHash: '#A8A8B9',
    textGray: '#BFBFBF',
    textAsh: '#F3F2F1',
    tickGray: '#BDBDBD',
    tabColor: '#6B7280',
    warning: '#e3be5a',
    paypal: '#FBD302',
    inactive: '#E1E8ED',
    active: '#737373',
    deepActive: '#646464',
    progress: '#3BA755',
    progressBg: '#BFBFBF',
    hashBackGround: '#F5F3F3',
    hashBackGroundL2: '#F3F3F3',
    hashBackGroundL3: '#F2F2F2',
    hashBackGroundL4: '#F6F6F6',
    hashHomeBackGround: '#EDEDED',
    hashHomeBackGroundL2: '#F9F9F9',
    hashHomeBackGroundL3: '#D3D3D3',
    advertBlue: '#C5E5FB',
    trackingBlue: '#D9F8FF',
    pendingBlue: '#ECF9FF',
    trackingBlueDark: '#009DBF',
    advertBlueDark: '#01446C',
    advertGreen: '#82FEBC',
    advertGreenLight: '#E6FFEF',
    advertGreenDark: '#0F8345',
    price: '#14AE5C',
    topup: '#46B97C',
    trackingGreen: '#DBF6E5',
    trackingGreenDark: '#00BF47',
    star: '#FFD700',
    trackingYellow: '#FFF5C0',
    trackingYellowDark: '#EAC608',
    modalOverlay: 'rgba(31, 32, 33, 0.4)',

    tint: tintColorLight,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorLight,
  },
  dark: {
    text: '#fff',
    background: '#000',
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
  },
};

export const SIZES = {
  sizeOne: 8,
  sizeTwo: 9,
  sizeThree: 10,
  sizeFour: 11,
  sizeFive: 12,
  sizeFiveB: 13,
  sizeFiveC: 14,
  sizeSix: 15,
  sizeSixB: 16,
  sizeSixC: 17,
  sizeSeven: 18,
  sizeSevenB: 19,
  sizeEight: 20,
  sizeEightA: 22,
  sizeEightB: 23,
  sizeNine: 25,
  sizeNineB: 28,
  sizeTen: 30,
  sizeEleven: 40,
};

export const IMAGES = {
  FrameWS1: require('../shared/assets/images/png/FrameWS1.png'),
  FrameWS1sub: require('../shared/assets/images/png/FrameWS1sub.png'),
  FrameWS2: require('../shared/assets/images/png/FrameWS2.png'),
  FrameWS2sub: require('../shared/assets/images/png/FrameWS2sub.png'),
  FrameWS3: require('../shared/assets/images/png/FrameWS3.png'),
  FrameWS3sub: require('../shared/assets/images/png/FrameWS3sub.png'),
  ProfileImage: require('../shared/assets/images/png/profile_image.png'),
  AdvertShirts: require('../shared/assets/images/png/Advert_Shirts.png'),
  SneakerSale: require('../shared/assets/images/png/SneakerSale.png'),
  ShoeFem: require('../shared/assets/images/png/ShoeFem.png'),
};
