#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo  :::::::::::::::::::::::::::::: &&
echo  👷‍♀️ 🔨🛠🔨🛠🔨🛠🔨🛠 🛠🔨🛠🔨🛠 🛠👷‍♀️  &&
echo  :::::Searching for Bugs::::::: &&
echo  :::::::::::::::::::::::::::::: &&
npx lint-staged &&
npm run lint:fix &&
npm run format
